controller_list:
  - name: fake_left_arm_controller
    joints:
      - ur5_left_shoulder_pan_joint
      - ur5_left_shoulder_lift_joint
      - ur5_left_elbow_joint
      - ur5_left_wrist_1_joint
      - ur5_left_wrist_2_joint
      - ur5_left_wrist_3_joint
  - name: fake_right_arm_controller
    joints:
      - ur5_right_shoulder_pan_joint
      - ur5_right_shoulder_lift_joint
      - ur5_right_elbow_joint
      - ur5_right_wrist_1_joint
      - ur5_right_wrist_2_joint
      - ur5_right_wrist_3_joint
  - name: fake_left_gripper_controller
    joints:
      - ur5_left_gripper_joint
  - name: fake_right_gripper_controller
    joints:
      - ur5_right_gripper_joint
initial:  # Define initial robot poses.
  - group: left_arm
    pose: left_idle
  - group: right_arm
    pose: right_idle