left_arm:
  kinematics_solver: mpo_500_left_arm/IKFastKinematicsPlugin 
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
right_arm:
  kinematics_solver: mpo_500_right_arm/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5


#   kdl_kinematics_plugin/KDLKinematicsPlugin 
